import { DataType } from './type';
export const dataToRender: DataType[] = [
  {
    monthName: 'January',
    employeeRecords: [
      {
        employee: {
          name: 'Emman Tolosa B.',
        },
        date: {
          month: 'january',
          year: '2021',
        },
        monthRecord: [
          {
            day: '1',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '2',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '3',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '4',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '5',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '6',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '7',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '8',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '9',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '10',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '11',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '12',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '13',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '14',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '15',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '16',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '17',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '18',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '19',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '20',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '21',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '22',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '23',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '24',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '25',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '26',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '27',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '28',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '29',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '30',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '31',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
        ],
      },
      {
        employee: {
          name: 'Hatdog digididog',
        },
        date: {
          month: 'january',
          year: '2021',
        },
        monthRecord: [
          {
            day: '1',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '2',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '3',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '4',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '5',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '6',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '7',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '8',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '9',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '10',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '11',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '12',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '13',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '14',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '15',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '16',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '17',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '18',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '19',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '20',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '21',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '22',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '23',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '24',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '25',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '26',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '27',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '28',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '29',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '30',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '31',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
        ],
      },
      {
        employee: {
          name: 'Hatdog digididog2',
        },
        date: {
          month: 'january',
          year: '2021',
        },
        monthRecord: [
          {
            day: '1',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '2',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '3',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '4',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '5',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '6',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '7',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '8',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '9',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '10',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '11',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '12',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '13',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '14',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '15',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '16',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '17',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '18',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '19',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '20',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '21',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '22',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '23',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '24',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '25',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '26',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '27',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '28',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '29',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '30',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '31',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
        ],
      },
    ],
  },
  {
    monthName: 'Febuary',
    employeeRecords: [
      {
        employee: {
          name: 'Emman Tolosa B.',
        },
        date: {
          month: 'febuary',
          year: '2021',
        },
        monthRecord: [
          {
            day: '1',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '2',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '3',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '4',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '5',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '6',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '7',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '8',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '9',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '10',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '11',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '12',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '13',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '14',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '15',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '16',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '17',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '18',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '19',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '20',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '21',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '22',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '23',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '24',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '25',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '26',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '27',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '28',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '29',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '30',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '31',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
        ],
      },
      {
        employee: {
          name: 'Hatdog digididog',
        },
        date: {
          month: 'febuary',
          year: '2021',
        },
        monthRecord: [
          {
            day: '1',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '2',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '3',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '4',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '5',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '6',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '7',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '8',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '9',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '10',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '11',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '12',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '13',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '14',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '15',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '16',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '17',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '18',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '19',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '20',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '21',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '22',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '23',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '24',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '25',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '26',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '27',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '28',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '29',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '30',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '31',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
        ],
      },
      {
        employee: {
          name: 'Hatdog feb',
        },
        date: {
          month: 'febuary',
          year: '2021',
        },
        monthRecord: [
          {
            day: '1',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '2',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '3',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '4',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '5',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '6',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '7',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '8',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '9',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '10',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '11',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '12',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '13',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '14',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '15',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '16',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '17',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '18',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '19',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '20',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '21',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '22',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '23',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '24',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '25',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '26',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '27',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '28',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '29',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '30',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
          {
            day: '31',
            timeIn: '12:00 PM',
            timeOut: '1:00 PM',
            workStatus: 'early',
            attendanceStatus: 'late',
            note: 'tinatamad pumasok',
          },
        ],
      },
    ],
  },
];
